name: seriousgame
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  flame_audio: ^1.3.2
  flame_tiled: ^1.8.0
  animated_text_kit: ^4.2.1
  responsive_framework: ^0.2.0
  resize: ^1.0.0
  pixelarticons: ^0.4.0
  flame_forge2d: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_test: ^1.1.0
  test: ^1.14.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/aumonier.png
    - assets/images/badge1.png
    - assets/images/badge2.png
    - assets/images/badge3.png
    - assets/images/badge4.png
    - assets/images/badge5.png
    - assets/images/badge6.png
    - assets/images/badge7.png
    - assets/images/badge8.png
    - assets/images/badge9.png
    - assets/images/badge10.png
    - assets/images/badge11.png
    - assets/images/badge12.png
    - assets/images/badge13.png
    - assets/images/badge14.png
    - assets/images/badge15.png
    - assets/images/bag.png
    - assets/images/brocoliOne.png
    - assets/images/brocoliSon.png
    - assets/images/cms.png
    - assets/images/dieteticiene.png
    - assets/images/glycometre.png
    - assets/images/hi_bullet.png
    - assets/images/infirmiere.png
    - assets/images/insuline.png
    - assets/images/intercept_bullet.png
    - assets/images/intercept_bullet.png
    - assets/images/medecin.png
    - assets/images/objection_bullet.png
    - assets/images/physio.png
    - assets/images/pulsoxymetre.png
    - assets/images/stethoscope.png
    - assets/images/tabacologue.png
    - assets/images/tensiometre.png
    - assets/images/thermometre.png
    - assets/images/urgence.png
    - assets/images/user.png
    - assets/images/urgence.png
    - assets/tiles/
    - assets/tiles/tiles_sets/
    - assets/audio/

  fonts:
    - family: novem
      fonts:
        - asset: assets/fonts/novem.ttf
    - family: pixel
      fonts:
        - asset: assets/fonts/pixel_sans_serif.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
